[package]
name = "thuip"
version = "0.1.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"

[dependencies]
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"
ipaddress = "0.1.2"
